spring.application.name=main-service
server.port=8888
spring.cloud.config.server.git.uri=https://github.com/bielxrd/main-config-server.git
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.username=bielxrd
spring.cloud.config.server.git.password=

# Define o caminho dentro do repositorio git onde estao os arquivos de configuracao
spring.cloud.config.server.git.search-paths=config

# Essa config server para informar ao eureka nao cadastrar essa aplicacao como um client, o motivo disso e
# por conta que essa aplicacao atuara como eureka server, ou seja, vai centralizar a plataforma e nao pode ser registrar
eureka.client.register-with-eureka=false

# Nao buscar o registro dele mesmo.
eureka.client.fetch-registry=false

# Definindo o hostname do servidor eureka, por enquanto localhost pois estamos em desenvolvimento local
eureka.instance.hostname=main-service

# Desabilitando o modo de auto-preservacao do eureka server para evitar que ele pare de aceitar requisicoes
# O modo de preservacao do eureka e uma funcionalidade dele saber quando os servicos estao ativos ou nao, quando o servico estiver desativo
# Ele para de enviar heartbeats para o eureka server, e nesse caso
eureka.server.enable-self-preservation=false

# Especifica o prefixo que os clientes terao que bater para buscar as configuracoes no config server
spring.cloud.config.server.prefix=/config
