spring.application.name=notification-service
spring.cloud.config.uri=http://host.docker.internal:8888/config

## Indica que essa aplicacao e um cliente do config server
spring.config.import=configserver:

## Configuracao do Eureka Client para registrar este servico no Eureka Server, ou seja, url do servidor eureka
eureka.client.service-url.defaultZone=http://host.docker.internal:8888/eureka


eureka.instance.hostname=notification-service
eureka.instance.prefer-ip-address=false