spring.application.name=service-tasks

spring.cloud.config.uri=http://host.docker.internal:8888/config
## Indica que essa aplicacao e um cliente do config server
spring.config.import=configserver:

## Configuracao do Eureka Client para registrar este servico no Eureka Server, ou seja, url do servidor eureka
eureka.client.service-url.defaultZone=http://host.docker.internal:8888/eureka
# Definindo o hostname do servidor eureka, por enquanto localhost pois estamos em desenvolvimento local, mas a config acima ja define a url do eureka server
eureka.instance.hostname=task-service
eureka.instance.prefer-ip-address=false